<a href="https://colab.research.google.com/github/Deborshi1998/python-snippets/blob/main/Spark.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#  !pip install pyspark

**Import and Create Spark Session Object**

In [ ]:
from pyspark.sql import SparkSession

In [ ]:
spark = SparkSession.builder.appName('Practice').getOrCreate()

**Creating DataFrame**

In [ ]:
import pandas as pd
from datetime import datetime, date
from pyspark.sql import Row

In [ ]:
from pyspark.sql.functions import col

In [ ]:
data_df = spark.createDataFrame([Row(id=100, val=123, name="Test", date_time = datetime(2023, 1,1,13,0)),
                                 Row(id=200, val=6123, name="Test2", date_time = datetime(2023, 1,2,13,0)),
                                 Row(id=300, val=13423, name="Test3", date_time = datetime(2023, 1,4,13,0))])

In [ ]:
data_df

DataFrame[id: bigint, val: bigint, name: string, date_time: timestamp]

In [ ]:
data_df_schema = spark.createDataFrame([Row(id=100, val=123, name="Test", date_time = datetime(2023, 1,1,13,0)),
                                 Row(id=200, val=6123, name="Test2", date_time = datetime(2023,2,4, 13,0)),
                                 Row(id=300, val=13423, name="Test3", date_time = datetime(2023, 3,3, 13,0))], schema="id int, val int, name string, date_time timestamp")

In [ ]:
data_df_schema

DataFrame[id: int, val: int, name: string, date_time: timestamp]

In [ ]:
import pandas as pd
data = {'id': [1, 2, 3], 'name': ['Alice', 'Bob', 'Charlie'],'age': [30, 35, 40]}
data_pandas = pd.DataFrame(data)
df_pandas = spark.createDataFrame(data_pandas)

In [ ]:
df_pandas.show()

+---+-------+---+
| id|   name|age|
+---+-------+---+
|  1|  Alice| 30|
|  2|    Bob| 35|
|  3|Charlie| 40|
+---+-------+---+

In [ ]:
df_pandas.printSchema()

root
 |-- id: long (nullable = true)
 |-- name: string (nullable = true)
 |-- age: long (nullable = true)

In [ ]:
df_pandas.describe().show()

+-------+---+-------+----+
|summary| id|   name| age|
+-------+---+-------+----+
|  count|  3|      3|   3|
|   mean|2.0|   NULL|35.0|
| stddev|1.0|   NULL| 5.0|
|    min|  1|  Alice|  30|
|    max|  3|Charlie|  40|
+-------+---+-------+----+

In [ ]:
df_pandas.describe()

DataFrame[summary: string, id: string, name: string, age: string]

In [ ]:
df_pandas.columns

['id', 'name', 'age']

In [ ]:
df_pandas.show(vertical=True)

-RECORD 0-------
 id   | 1
 name | Alice
 age  | 30
-RECORD 1-------
 id   | 2
 name | Bob
 age  | 35
-RECORD 2-------
 id   | 3
 name | Charlie
 age  | 40

**Collect Data**

In [ ]:
df_pandas.count()

3

In [ ]:
df_pandas.collect()

[Row(id=1, name='Alice', age=30),
 Row(id=2, name='Bob', age=35),
 Row(id=3, name='Charlie', age=40)]

In [ ]:
all_rows = df_pandas.collect()

In [ ]:
all_rows

[Row(id=1, name='Alice', age=30),
 Row(id=2, name='Bob', age=35),
 Row(id=3, name='Charlie', age=40)]

In [ ]:
two_rows = df_pandas.take(2)

In [ ]:
two_rows_head = df_pandas.head(2)

In [ ]:
two_rows_head

[Row(id=1, name='Alice', age=30), Row(id=2, name='Bob', age=35)]

In [ ]:
df_pandas.tail(2)

[Row(id=2, name='Bob', age=35), Row(id=3, name='Charlie', age=40)]

In [ ]:
type(df_pandas)

pyspark.sql.dataframe.DataFrame

**Convert to Pandas**

In [ ]:
pandas_df = df_pandas.toPandas()

In [ ]:
pandas_df

   id     name  age
0   1    Alice   30
1   2      Bob   35
2   3  Charlie   40

In [ ]:
type(pandas_df)

pandas.core.frame.DataFrame

# Data Manipulation

***
**Import from different sources**

In [ ]:
#CSV format
#Using read.csv, specific method
df_csv = spark.read.csv("/content/sample_data/california_housing_train.csv", header=True, inferSchema=True)

In [ ]:
#Using general method
df_csv_2 = spark.read.format("csv") \
          .option("header", "true") \
          .option("inferSchema", "true") \
          .load("/content/sample_data/california_housing_train.csv")

In [ ]:
df_csv.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|  -114.31|   34.19|              15.0|     5612.0|        1283.0|    1015.0|     472.0|       1.4936|           66900.0|
|  -114.47|    34.4|              19.0|     7650.0|        1901.0|    1129.0|     463.0|         1.82|           80100.0|
|  -114.56|   33.69|              17.0|      720.0|         174.0|     333.0|     117.0|       1.6509|           85700.0|
|  -114.57|   33.64|              14.0|     1501.0|         337.0|     515.0|     226.0|       3.1917|           73400.0|
|  -114.57|   33.57|              20.0|     1454.0|         326.0|     624.0|     262.0|        1.925|           65500.0|
|  -114.58|   33.63|              29.0|     1387.0|         236.0|     671.0|     239.0|       3.3438|           74000.0|
|  -114.58|   33.61|              25.0|     2907.0|         680.0|    1841.0|     633.0|       2.6768|           82400.0|
|  -114.59|   34.83|              41.0|      812.0|         168.0|     375.0|     158.0|       1.7083|           48500.0|
|  -114.59|   33.61|              34.0|     4789.0|        1175.0|    3134.0|    1056.0|       2.1782|           58400.0|
|   -114.6|   34.83|              46.0|     1497.0|         309.0|     787.0|     271.0|       2.1908|           48100.0|
|   -114.6|   33.62|              16.0|     3741.0|         801.0|    2434.0|     824.0|       2.6797|           86500.0|
|   -114.6|    33.6|              21.0|     1988.0|         483.0|    1182.0|     437.0|        1.625|           62000.0|
|  -114.61|   34.84|              48.0|     1291.0|         248.0|     580.0|     211.0|       2.1571|           48600.0|
|  -114.61|   34.83|              31.0|     2478.0|         464.0|    1346.0|     479.0|        3.212|           70400.0|
|  -114.63|   32.76|              15.0|     1448.0|         378.0|     949.0|     300.0|       0.8585|           45000.0|
|  -114.65|   34.89|              17.0|     2556.0|         587.0|    1005.0|     401.0|       1.6991|           69100.0|
|  -114.65|    33.6|              28.0|     1678.0|         322.0|     666.0|     256.0|       2.9653|           94900.0|
|  -114.65|   32.79|              21.0|       44.0|          33.0|      64.0|      27.0|       0.8571|           25000.0|
|  -114.66|   32.74|              17.0|     1388.0|         386.0|     775.0|     320.0|       1.2049|           44000.0|
|  -114.67|   33.92|              17.0|       97.0|          24.0|      29.0|      15.0|       1.2656|           27500.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
only showing top 20 rows

In [ ]:
type(df_csv_2)

pyspark.sql.dataframe.DataFrame

In [ ]:
house_val_col = df_csv.select("median_house_value")

In [ ]:
house_val_col.show(10)

+------------------+
|median_house_value|
+------------------+
|           66900.0|
|           80100.0|
|           85700.0|
|           73400.0|
|           65500.0|
|           74000.0|
|           82400.0|
|           48500.0|
|           58400.0|
|           48100.0|
+------------------+
only showing top 10 rows

In [ ]:
df_csv.count()

17000

In [ ]:
df_csv.select("median_house_value", "population").show()

+------------------+----------+
|median_house_value|population|
+------------------+----------+
|           66900.0|    1015.0|
|           80100.0|    1129.0|
|           85700.0|     333.0|
|           73400.0|     515.0|
|           65500.0|     624.0|
|           74000.0|     671.0|
|           82400.0|    1841.0|
|           48500.0|     375.0|
|           58400.0|    3134.0|
|           48100.0|     787.0|
|           86500.0|    2434.0|
|           62000.0|    1182.0|
|           48600.0|     580.0|
|           70400.0|    1346.0|
|           45000.0|     949.0|
|           69100.0|    1005.0|
|           94900.0|     666.0|
|           25000.0|      64.0|
|           44000.0|     775.0|
|           27500.0|      29.0|
+------------------+----------+
only showing top 20 rows

In [ ]:
# Some more ways of selecting columns
# from pyspark.sql.functions import col

# df_customer.select(
#   col("c_custkey"),
#   col("c_acctbal")
# )

#Below accepts expression
# from pyspark.sql.functions import expr

# df_customer.select(
#   expr("c_custkey"),
#   expr("c_acctbal")
# )

#Below accepts SQL expression
# df_customer.selectExpr(
#   "c_custkey as key",
#   "round(c_acctbal) as account_rounded"
# )
# df_customer.select(
#   "c_custkey",
#   "c_acctbal"
# )
# df_customer.select(
#   df_customer["c_custkey"],
#   df_customer["c_acctbal"]
# )
# df_customer.select(
#   df_customer.c_custkey,
#   df_customer.c_acctbal
# )

In [ ]:
#col is needed for complex work
# from pyspark.sql.functions import col

# # Simple selection: both work
# df.select("age")
# df.select(col("age"))

# # Arithmetic operations: must use col()
# df.select(col("age") + 1)

# # Renaming a column: must use col()
# df.select(col("age").alias("new_age"))

In [ ]:
df_newCol = df_csv.withColumn("room_by_bedroom_ratio", df_csv["total_rooms"]/df_csv["total_bedrooms"])

In [ ]:
df_newCol.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|room_by_bedroom_ratio|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------------+
|  -114.31|   34.19|              15.0|     5612.0|        1283.0|    1015.0|     472.0|       1.4936|           66900.0|    4.374123148869836|
|  -114.47|    34.4|              19.0|     7650.0|        1901.0|    1129.0|     463.0|         1.82|           80100.0|    4.024197790636507|
|  -114.56|   33.69|              17.0|      720.0|         174.0|     333.0|     117.0|       1.6509|           85700.0|    4.137931034482759|
|  -114.57|   33.64|              14.0|     1501.0|         337.0|     515.0|     226.0|       3.1917|           73400.0|    4.454005934718101|
|  -114.57|   33.57|              20.0|     1454.0|         326.0|     624.0|     262.0|        1.925|           65500.0|    4.460122699386503|
|  -114.58|   33.63|              29.0|     1387.0|         236.0|     671.0|     239.0|       3.3438|           74000.0|    5.877118644067797|
|  -114.58|   33.61|              25.0|     2907.0|         680.0|    1841.0|     633.0|       2.6768|           82400.0|                4.275|
|  -114.59|   34.83|              41.0|      812.0|         168.0|     375.0|     158.0|       1.7083|           48500.0|    4.833333333333333|
|  -114.59|   33.61|              34.0|     4789.0|        1175.0|    3134.0|    1056.0|       2.1782|           58400.0|    4.075744680851064|
|   -114.6|   34.83|              46.0|     1497.0|         309.0|     787.0|     271.0|       2.1908|           48100.0|    4.844660194174757|
|   -114.6|   33.62|              16.0|     3741.0|         801.0|    2434.0|     824.0|       2.6797|           86500.0|    4.670411985018727|
|   -114.6|    33.6|              21.0|     1988.0|         483.0|    1182.0|     437.0|        1.625|           62000.0|    4.115942028985507|
|  -114.61|   34.84|              48.0|     1291.0|         248.0|     580.0|     211.0|       2.1571|           48600.0|    5.205645161290323|
|  -114.61|   34.83|              31.0|     2478.0|         464.0|    1346.0|     479.0|        3.212|           70400.0|   5.3405172413793105|
|  -114.63|   32.76|              15.0|     1448.0|         378.0|     949.0|     300.0|       0.8585|           45000.0|   3.8306878306878307|
|  -114.65|   34.89|              17.0|     2556.0|         587.0|    1005.0|     401.0|       1.6991|           69100.0|    4.354344122657581|
|  -114.65|    33.6|              28.0|     1678.0|         322.0|     666.0|     256.0|       2.9653|           94900.0|    5.211180124223603|
|  -114.65|   32.79|              21.0|       44.0|          33.0|      64.0|      27.0|       0.8571|           25000.0|   1.3333333333333333|
|  -114.66|   32.74|              17.0|     1388.0|         386.0|     775.0|     320.0|       1.2049|           44000.0|   3.5958549222797926|
|  -114.67|   33.92|              17.0|       97.0|          24.0|      29.0|      15.0|       1.2656|           27500.0|    4.041666666666667|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+---------------------+
only showing top 20 rows

In [ ]:
df_csv.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|  -114.31|   34.19|              15.0|     5612.0|        1283.0|    1015.0|     472.0|       1.4936|           66900.0|
|  -114.47|    34.4|              19.0|     7650.0|        1901.0|    1129.0|     463.0|         1.82|           80100.0|
|  -114.56|   33.69|              17.0|      720.0|         174.0|     333.0|     117.0|       1.6509|           85700.0|
|  -114.57|   33.64|              14.0|     1501.0|         337.0|     515.0|     226.0|       3.1917|           73400.0|
|  -114.57|   33.57|              20.0|     1454.0|         326.0|     624.0|     262.0|        1.925|           65500.0|
|  -114.58|   33.63|              29.0|     1387.0|         236.0|     671.0|     239.0|       3.3438|           74000.0|
|  -114.58|   33.61|              25.0|     2907.0|         680.0|    1841.0|     633.0|       2.6768|           82400.0|
|  -114.59|   34.83|              41.0|      812.0|         168.0|     375.0|     158.0|       1.7083|           48500.0|
|  -114.59|   33.61|              34.0|     4789.0|        1175.0|    3134.0|    1056.0|       2.1782|           58400.0|
|   -114.6|   34.83|              46.0|     1497.0|         309.0|     787.0|     271.0|       2.1908|           48100.0|
|   -114.6|   33.62|              16.0|     3741.0|         801.0|    2434.0|     824.0|       2.6797|           86500.0|
|   -114.6|    33.6|              21.0|     1988.0|         483.0|    1182.0|     437.0|        1.625|           62000.0|
|  -114.61|   34.84|              48.0|     1291.0|         248.0|     580.0|     211.0|       2.1571|           48600.0|
|  -114.61|   34.83|              31.0|     2478.0|         464.0|    1346.0|     479.0|        3.212|           70400.0|
|  -114.63|   32.76|              15.0|     1448.0|         378.0|     949.0|     300.0|       0.8585|           45000.0|
|  -114.65|   34.89|              17.0|     2556.0|         587.0|    1005.0|     401.0|       1.6991|           69100.0|
|  -114.65|    33.6|              28.0|     1678.0|         322.0|     666.0|     256.0|       2.9653|           94900.0|
|  -114.65|   32.79|              21.0|       44.0|          33.0|      64.0|      27.0|       0.8571|           25000.0|
|  -114.66|   32.74|              17.0|     1388.0|         386.0|     775.0|     320.0|       1.2049|           44000.0|
|  -114.67|   33.92|              17.0|       97.0|          24.0|      29.0|      15.0|       1.2656|           27500.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
only showing top 20 rows

In [ ]:
from pyspark.sql.functions import col
df_newCol2 = df_csv.withColumn("room_by_bedroom_percen", col("total_rooms")/col("total_bedrooms")).show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+----------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|room_by_bedroom_percen|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+----------------------+
|  -114.31|   34.19|              15.0|     5612.0|        1283.0|    1015.0|     472.0|       1.4936|           66900.0|     4.374123148869836|
|  -114.47|    34.4|              19.0|     7650.0|        1901.0|    1129.0|     463.0|         1.82|           80100.0|     4.024197790636507|
|  -114.56|   33.69|              17.0|      720.0|         174.0|     333.0|     117.0|       1.6509|           85700.0|     4.137931034482759|
|  -114.57|   33.64|              14.0|     1501.0|         337.0|     515.0|     226.0|       3.1917|           73400.0|     4.454005934718101|
|  -114.57|   33.57|              20.0|     1454.0|         326.0|     624.0|     262.0|        1.925|           65500.0|     4.460122699386503|
|  -114.58|   33.63|              29.0|     1387.0|         236.0|     671.0|     239.0|       3.3438|           74000.0|     5.877118644067797|
|  -114.58|   33.61|              25.0|     2907.0|         680.0|    1841.0|     633.0|       2.6768|           82400.0|                 4.275|
|  -114.59|   34.83|              41.0|      812.0|         168.0|     375.0|     158.0|       1.7083|           48500.0|     4.833333333333333|
|  -114.59|   33.61|              34.0|     4789.0|        1175.0|    3134.0|    1056.0|       2.1782|           58400.0|     4.075744680851064|
|   -114.6|   34.83|              46.0|     1497.0|         309.0|     787.0|     271.0|       2.1908|           48100.0|     4.844660194174757|
|   -114.6|   33.62|              16.0|     3741.0|         801.0|    2434.0|     824.0|       2.6797|           86500.0|     4.670411985018727|
|   -114.6|    33.6|              21.0|     1988.0|         483.0|    1182.0|     437.0|        1.625|           62000.0|     4.115942028985507|
|  -114.61|   34.84|              48.0|     1291.0|         248.0|     580.0|     211.0|       2.1571|           48600.0|     5.205645161290323|
|  -114.61|   34.83|              31.0|     2478.0|         464.0|    1346.0|     479.0|        3.212|           70400.0|    5.3405172413793105|
|  -114.63|   32.76|              15.0|     1448.0|         378.0|     949.0|     300.0|       0.8585|           45000.0|    3.8306878306878307|
|  -114.65|   34.89|              17.0|     2556.0|         587.0|    1005.0|     401.0|       1.6991|           69100.0|     4.354344122657581|
|  -114.65|    33.6|              28.0|     1678.0|         322.0|     666.0|     256.0|       2.9653|           94900.0|     5.211180124223603|
|  -114.65|   32.79|              21.0|       44.0|          33.0|      64.0|      27.0|       0.8571|           25000.0|    1.3333333333333333|
|  -114.66|   32.74|              17.0|     1388.0|         386.0|     775.0|     320.0|       1.2049|           44000.0|    3.5958549222797926|
|  -114.67|   33.92|              17.0|       97.0|          24.0|      29.0|      15.0|       1.2656|           27500.0|     4.041666666666667|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+----------------------+
only showing top 20 rows

In [ ]:
#Rename
# df_customer_flag_renamed = df_customer_flag.withColumnRenamed("balance_flag", "balance_flag_renamed")

In [ ]:
#Drop Columns
# df_customer_flag_renamed.drop("c_phone", "balance_flag_renamed")

NameError: name 'df_customer_flag_renamed' is not defined

In [ ]:
#Change datatype
# from pyspark.sql.functions import col

# df_casted = df_customer.withColumn("c_custkey", col("c_custkey").cast(StringType()))
# print(type(df_casted))

**Row Manipulation**

In [ ]:
pd_hotels = pd.read_csv("/content/sample_data/hotels.csv")
pd_reviews = pd.read_csv("/content/sample_data/reviews.csv")
pd_users = pd.read_csv("/content/sample_data/users.csv")

In [ ]:
pd_hotels.head()

,hotel_id,hotel_name,city,country,star_rating,lat,lon,cleanliness_base,comfort_base,facilities_base,location_base,staff_base,value_for_money_base
0,1,The Azure Tower,New York,United States,5,40.7580,-73.9855,9.1,8.8,8.9,9.5,8.6,8.0
1,2,The Royal Compass,London,United Kingdom,5,51.5072,-0.1276,9.0,9.2,8.8,9.4,9.0,7.9
2,3,L'Étoile Palace,Paris,France,5,48.8566,2.3522,8.8,9.4,8.7,9.6,9.3,8.1
3,4,Kyo-to Grand,Tokyo,Japan,5,35.6895,139.6917,9.6,9.0,9.3,8.5,9.5,8.2
4,5,The Golden Oasis,Dubai,United Arab Emirates,5,25.2769,55.2962,9.3,9.5,9.6,8.9,9.4,8.5

In [ ]:
pd_hotels['city'].value_counts()

city
New York          1
London            1
Paris             1
Tokyo             1
Dubai             1
Singapore         1
Sydney            1
Rio de Janeiro    1
Berlin            1
Toronto           1
Shanghai          1
Mexico City       1
Mumbai            1
Rome              1
Cape Town         1
Seoul             1
Moscow            1
Cairo             1
Barcelona         1
Bangkok           1
Istanbul          1
Amsterdam         1
Buenos Aires      1
Lagos             1
Wellington        1
Name: count, dtype: int64

In [ ]:
pd_reviews.head()

,review_id,user_id,hotel_id,review_date,score_overall,score_cleanliness,score_comfort,score_facilities,score_location,score_staff,score_value_for_money,review_text
0,1,1600,1,2022-10-07,8.7,8.6,8.7,8.5,9.0,8.8,8.7,Practice reduce young our because machine. Rec...
1,2,432,4,2020-03-24,9.1,10.0,9.1,9.0,8.6,9.4,8.6,Test cover traditional black. Process tell Mr ...
2,3,186,18,2023-12-18,8.8,9.7,8.8,8.3,8.7,8.1,8.6,Friend million student social study yeah. Grow...
3,4,1403,19,2022-06-22,8.9,9.0,8.8,8.5,9.6,9.1,8.3,Huge girl already remain truth behind card. Ap...
4,5,1723,17,2022-07-02,9.1,8.9,9.5,9.3,8.3,9.4,8.9,Cover feeling call community serve television ...

In [ ]:
pd_users.head()

   user_id user_gender         country age_group traveller_type   join_date
0        1      Female  United Kingdom     35-44           Solo  2024-09-29
1        2        Male  United Kingdom     25-34           Solo  2023-11-29
2        3      Female          Mexico     25-34         Family  2022-04-03
3        4        Male           India     35-44         Family  2023-12-02
4        5       Other           Japan     25-34           Solo  2021-12-18

In [ ]:
df_hotels = spark.createDataFrame(pd_hotels)
df_reviews = spark.createDataFrame(pd_reviews)
df_users = spark.createDataFrame(pd_users)

In [ ]:
df_hotels.show()

+--------+--------------------+--------------+--------------------+-----------+--------+----------+----------------+------------+---------------+-------------+----------+--------------------+
|hotel_id|          hotel_name|          city|             country|star_rating|     lat|       lon|cleanliness_base|comfort_base|facilities_base|location_base|staff_base|value_for_money_base|
+--------+--------------------+--------------+--------------------+-----------+--------+----------+----------------+------------+---------------+-------------+----------+--------------------+
|       1|     The Azure Tower|      New York|       United States|          5|  40.758|  -73.9855|             9.1|         8.8|            8.9|          9.5|       8.6|                 8.0|
|       2|   The Royal Compass|        London|      United Kingdom|          5| 51.5072|   -0.1276|             9.0|         9.2|            8.8|          9.4|       9.0|                 7.9|
|       3|     L'Étoile Palace|         Paris|              France|          5| 48.8566|    2.3522|             8.8|         9.4|            8.7|          9.6|       9.3|                 8.1|
|       4|        Kyo-to Grand|         Tokyo|               Japan|          5| 35.6895|  139.6917|             9.6|         9.0|            9.3|          8.5|       9.5|                 8.2|
|       5|    The Golden Oasis|         Dubai|United Arab Emirates|          5| 25.2769|   55.2962|             9.3|         9.5|            9.6|          8.9|       9.4|                 8.5|
|       6|   Marina Bay Zenith|     Singapore|           Singapore|          5| 1.29027|103.851959|             9.2|         9.1|            9.4|          9.7|       9.1|                 8.3|
|       7|Sydney Harbour Grand|        Sydney|           Australia|          5|-33.8651|  151.2099|             8.9|         9.0|            8.5|          9.8|       8.9|                 8.4|
|       8|      Copacabana Lux|Rio de Janeiro|              Brazil|          5|-22.9068|  -43.1729|             9.0|         8.7|            8.6|          9.5|       8.8|                 8.6|
|       9|  Berlin Mitte Elite|        Berlin|             Germany|          5|   52.52|    13.405|             9.3|         9.2|            9.0|          9.1|       9.1|                 8.7|
|      10|     The Maple Grove|       Toronto|              Canada|          5| 43.6532|  -79.3832|             9.4|         9.3|            9.2|          8.8|       9.2|                 8.8|
|      11|     The Bund Palace|      Shanghai|               China|          5| 31.2304|  121.4737|             9.1|         9.0|            9.2|          9.6|       9.0|                 8.9|
|      12|       Aztec Heights|   Mexico City|              Mexico|          5| 19.4326|  -99.1332|             8.7|         8.9|            8.5|          9.0|       8.7|                 8.5|
|      13|  The Gateway Royale|        Mumbai|               India|          5|  19.076|   72.8777|             8.9|         8.8|            8.7|          9.2|       8.8|                 8.6|
|      14|   Colosseum Gardens|          Rome|               Italy|          5| 41.9028|   12.4964|             9.2|         9.1|            8.9|          9.8|       9.0|                 8.7|
|      15| Table Mountain View|     Cape Town|        South Africa|          5|-33.9249|   18.4241|             9.0|         9.2|            8.8|          9.5|       9.2|                 8.4|
|      16|     Han River Oasis|         Seoul|         South Korea|          5| 37.5665|   126.978|             9.3|         9.4|            9.1|          8.9|       9.3|                 8.5|
|      17|      Kremlin Suites|        Moscow|              Russia|          5| 55.7558|   37.6173|             9.1|         9.3|            9.0|          9.0|       9.1|                 8.6|
|      18|       Nile Grandeur|         Cairo|               Egypt|          5| 30.0444|   31.2357|             8.8|         8.7|            8.6|          9.1|       8.7|                 8.4|
|      19|     Gaudi's Retreat|     Barcelona|               Spain|          5| 41.3851|    2.1734|             9.2|         9.1|            8.9|          9.7|       9.0|                 8.8|
|      20|   The Orchid Palace|       Bangkok|            Thailand|          5| 13.7563|  100.5018|             9.0|         9.2|            9.1|          9.4|       9.1|                 8.6|
+--------+--------------------+--------------+--------------------+-----------+--------+----------+----------------+------------+---------------+-------------+----------+--------------------+
only showing top 20 rows

In [ ]:
df_hotels.filter(col('country') == 'United States').show()

+--------+---------------+--------+-------------+-----------+------+--------+----------------+------------+---------------+-------------+----------+--------------------+
|hotel_id|     hotel_name|    city|      country|star_rating|   lat|     lon|cleanliness_base|comfort_base|facilities_base|location_base|staff_base|value_for_money_base|
+--------+---------------+--------+-------------+-----------+------+--------+----------------+------------+---------------+-------------+----------+--------------------+
|       1|The Azure Tower|New York|United States|          5|40.758|-73.9855|             9.1|         8.8|            8.9|          9.5|       8.6|                 8.0|
+--------+---------------+--------+-------------+-----------+------+--------+----------------+------------+---------------+-------------+----------+--------------------+

In [ ]:
df_hotels.filter((col('country') == 'United States') & (col('city') == 'New York')).show()

+--------+---------------+--------+-------------+-----------+------+--------+----------------+------------+---------------+-------------+----------+--------------------+
|hotel_id|     hotel_name|    city|      country|star_rating|   lat|     lon|cleanliness_base|comfort_base|facilities_base|location_base|staff_base|value_for_money_base|
+--------+---------------+--------+-------------+-----------+------+--------+----------------+------------+---------------+-------------+----------+--------------------+
|       1|The Azure Tower|New York|United States|          5|40.758|-73.9855|             9.1|         8.8|            8.9|          9.5|       8.6|                 8.0|
+--------+---------------+--------+-------------+-----------+------+--------+----------------+------------+---------------+-------------+----------+--------------------+

In [ ]:
#Does list value exist
country_list = ['India', 'Italy','Russia','Vacitan']
df_hotels.filter(col('country').isin(country_list)).show()

+--------+------------------+------+-------+-----------+-------+-------+----------------+------------+---------------+-------------+----------+--------------------+
|hotel_id|        hotel_name|  city|country|star_rating|    lat|    lon|cleanliness_base|comfort_base|facilities_base|location_base|staff_base|value_for_money_base|
+--------+------------------+------+-------+-----------+-------+-------+----------------+------------+---------------+-------------+----------+--------------------+
|      13|The Gateway Royale|Mumbai|  India|          5| 19.076|72.8777|             8.9|         8.8|            8.7|          9.2|       8.8|                 8.6|
|      14| Colosseum Gardens|  Rome|  Italy|          5|41.9028|12.4964|             9.2|         9.1|            8.9|          9.8|       9.0|                 8.7|
|      17|    Kremlin Suites|Moscow| Russia|          5|55.7558|37.6173|             9.1|         9.3|            9.0|          9.0|       9.1|                 8.6|
+--------+------------------+------+-------+-----------+-------+-------+----------------+------------+---------------+-------------+----------+--------------------+

* We can drop null rows, for any null value or all null values
* Apply only to a subset of columns
* Fill missing values
* Replace value

In [ ]:
# df_customer_no_nulls = df_customer.na.drop()
# df_customer_no_nulls = df_customer.na.drop("any")

# df_customer_no_nulls = df_customer.na.drop("all")

# df_customer_no_nulls = df_customer.na.drop("all", subset=["c_acctbal", "c_custkey"])
# df_customer_filled = df_customer.na.fill("0", subset=["c_acctbal"])

# df_customer_phone_filled = df_customer.na.replace([""], ["UNKNOWN"], subset=["c_phone"])

In [ ]:
#Drop Duplicate
new_salary_data = salary_data.dropDuplicates().show()

In [ ]:
import pyspark.sql.functions as fun

In [ ]:
df_hotels.select(fun.sum(col('value_for_money_base')).alias("sum_val")).show()

+-------+
|sum_val|
+-------+
|  212.8|
+-------+

In [ ]:
df_hotels.agg({'value_for_money_base': 'sum'}).show()

+-------------------------+
|sum(value_for_money_base)|
+-------------------------+
|                    212.8|
+-------------------------+

In [ ]:
df_hotels.orderBy(col('value_for_money_base').desc()).show()

+--------+--------------------+--------------+--------------------+-----------+--------+--------+----------------+------------+---------------+-------------+----------+--------------------+
|hotel_id|          hotel_name|          city|             country|star_rating|     lat|     lon|cleanliness_base|comfort_base|facilities_base|location_base|staff_base|value_for_money_base|
+--------+--------------------+--------------+--------------------+-----------+--------+--------+----------------+------------+---------------+-------------+----------+--------------------+
|      22|   Canal House Grand|     Amsterdam|         Netherlands|          5| 52.3676|  4.9041|             9.4|         9.1|            9.0|          9.6|       9.2|                 8.9|
|      11|     The Bund Palace|      Shanghai|               China|          5| 31.2304|121.4737|             9.1|         9.0|            9.2|          9.6|       9.0|                 8.9|
|      19|     Gaudi's Retreat|     Barcelona|               Spain|          5| 41.3851|  2.1734|             9.2|         9.1|            8.9|          9.7|       9.0|                 8.8|
|      10|     The Maple Grove|       Toronto|              Canada|          5| 43.6532|-79.3832|             9.4|         9.3|            9.2|          8.8|       9.2|                 8.8|
|      25|      The Kiwi Grand|    Wellington|         New Zealand|          5|-41.2865|174.7762|             9.3|         9.2|            9.1|          9.0|       9.1|                 8.8|
|       9|  Berlin Mitte Elite|        Berlin|             Germany|          5|   52.52|  13.405|             9.3|         9.2|            9.0|          9.1|       9.1|                 8.7|
|      14|   Colosseum Gardens|          Rome|               Italy|          5| 41.9028| 12.4964|             9.2|         9.1|            8.9|          9.8|       9.0|                 8.7|
|      23|      Tango Boutique|  Buenos Aires|           Argentina|          5|-34.6037|-58.3816|             8.9|         8.8|            8.7|          9.0|       8.8|                 8.7|
|       8|      Copacabana Lux|Rio de Janeiro|              Brazil|          5|-22.9068|-43.1729|             9.0|         8.7|            8.6|          9.5|       8.8|                 8.6|
|      13|  The Gateway Royale|        Mumbai|               India|          5|  19.076| 72.8777|             8.9|         8.8|            8.7|          9.2|       8.8|                 8.6|
|      17|      Kremlin Suites|        Moscow|              Russia|          5| 55.7558| 37.6173|             9.1|         9.3|            9.0|          9.0|       9.1|                 8.6|
|      20|   The Orchid Palace|       Bangkok|            Thailand|          5| 13.7563|100.5018|             9.0|         9.2|            9.1|          9.4|       9.1|                 8.6|
|       5|    The Golden Oasis|         Dubai|United Arab Emirates|          5| 25.2769| 55.2962|             9.3|         9.5|            9.6|          8.9|       9.4|                 8.5|
|      16|     Han River Oasis|         Seoul|         South Korea|          5| 37.5665| 126.978|             9.3|         9.4|            9.1|          8.9|       9.3|                 8.5|
|      12|       Aztec Heights|   Mexico City|              Mexico|          5| 19.4326|-99.1332|             8.7|         8.9|            8.5|          9.0|       8.7|                 8.5|
|      21|   The Bosphorus Inn|      Istanbul|              Turkey|          5| 41.0082| 28.9784|             9.1|         9.0|            8.8|          9.3|       8.9|                 8.5|
|       7|Sydney Harbour Grand|        Sydney|           Australia|          5|-33.8651|151.2099|             8.9|         9.0|            8.5|          9.8|       8.9|                 8.4|
|      15| Table Mountain View|     Cape Town|        South Africa|          5|-33.9249| 18.4241|             9.0|         9.2|            8.8|          9.5|       9.2|                 8.4|
|      18|       Nile Grandeur|         Cairo|               Egypt|          5| 30.0444| 31.2357|             8.8|         8.7|            8.6|          9.1|       8.7|                 8.4|
|      24|  The Savannah House|         Lagos|             Nigeria|          5|  6.5244|  3.3792|             8.7|         8.6|            8.5|          8.9|       8.6|                 8.4|
+--------+--------------------+--------------+--------------------+-----------+--------+--------+----------------+------------+---------------+-------------+----------+--------------------+
only showing top 20 rows

# Group by and other operations

In [ ]:
df_salary = spark.read.format("csv") \
          .option("header", "true") \
          .option("inferSchema", "true") \
          .load("/content/sample_data/Salary_Data.csv")

In [ ]:
df_salary.describe().show()

+-------+-----------------+------+---------------+---------------+-------------------+------------------+
|summary|              Age|Gender|Education Level|      Job Title|Years of Experience|            Salary|
+-------+-----------------+------+---------------+---------------+-------------------+------------------+
|  count|             6702|  6702|           6701|           6702|               6701|              6699|
|   mean|33.62085944494181|  NULL|           NULL|           NULL|  8.094687360095508|115326.96477086132|
| stddev|7.614632626251299|  NULL|           NULL|           NULL|  6.059003056634108| 52786.18391068295|
|    min|               21|Female|     Bachelor's|Account Manager|                0.0|               350|
|    max|               62| Other|            phD|  Web Developer|               34.0|            250000|
+-------+-----------------+------+---------------+---------------+-------------------+------------------+

In [ ]:
df_salary.show(10)

+---+------+---------------+--------------------+-------------------+------+
|Age|Gender|Education Level|           Job Title|Years of Experience|Salary|
+---+------+---------------+--------------------+-------------------+------+
| 32|  Male|     Bachelor's|   Software Engineer|                5.0| 90000|
| 28|Female|       Master's|        Data Analyst|                3.0| 65000|
| 45|  Male|            PhD|      Senior Manager|               15.0|150000|
| 36|Female|     Bachelor's|     Sales Associate|                7.0| 60000|
| 52|  Male|       Master's|            Director|               20.0|200000|
| 29|  Male|     Bachelor's|   Marketing Analyst|                2.0| 55000|
| 42|Female|       Master's|     Product Manager|               12.0|120000|
| 31|  Male|     Bachelor's|       Sales Manager|                4.0| 80000|
| 26|Female|     Bachelor's|Marketing Coordin...|                1.0| 45000|
| 38|  Male|            PhD|    Senior Scientist|               10.0|110000|
+---+------+---------------+--------------------+-------------------+------+
only showing top 10 rows

In [ ]:
#Groupby
df_salary.groupBy("Gender").agg(fun.avg("Salary")).show()

+------+------------------+
|Gender|       avg(Salary)|
+------+------------------+
|  NULL|              NULL|
|Female|107888.99867241952|
| Other|125869.85714285714|
|  Male|121389.87091503268|
+------+------------------+

In [ ]:
(df_salary.groupBy("Gender").avg('Salary')).alias('sum_val').show()

+------+------------------+
|Gender|       avg(Salary)|
+------+------------------+
|  NULL|              NULL|
|Female|107888.99867241952|
| Other|125869.85714285714|
|  Male|121389.87091503268|
+------+------------------+

In [ ]:


df_chained = (
    df_salary.filter(col("Education Level") == "Master's")
    .groupBy(col("Gender"))
    .agg(fun.avg(col("Salary")).alias("avg_sal_val"))
    .sort(col("Gender").desc())
)

display(df_chained)

DataFrame[Gender: string, avg_sal_val: double]

In [ ]:
df_chained.show()

+------+------------------+
|Gender|       avg_sal_val|
+------+------------------+
|  Male|151797.75280898876|
|Female|160201.00502512563|
+------+------------------+

# Optimization

In [ ]:
df_csv.show()

+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|longitude|latitude|housing_median_age|total_rooms|total_bedrooms|population|households|median_income|median_house_value|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
|  -114.31|   34.19|              15.0|     5612.0|        1283.0|    1015.0|     472.0|       1.4936|           66900.0|
|  -114.47|    34.4|              19.0|     7650.0|        1901.0|    1129.0|     463.0|         1.82|           80100.0|
|  -114.56|   33.69|              17.0|      720.0|         174.0|     333.0|     117.0|       1.6509|           85700.0|
|  -114.57|   33.64|              14.0|     1501.0|         337.0|     515.0|     226.0|       3.1917|           73400.0|
|  -114.57|   33.57|              20.0|     1454.0|         326.0|     624.0|     262.0|        1.925|           65500.0|
|  -114.58|   33.63|              29.0|     1387.0|         236.0|     671.0|     239.0|       3.3438|           74000.0|
|  -114.58|   33.61|              25.0|     2907.0|         680.0|    1841.0|     633.0|       2.6768|           82400.0|
|  -114.59|   34.83|              41.0|      812.0|         168.0|     375.0|     158.0|       1.7083|           48500.0|
|  -114.59|   33.61|              34.0|     4789.0|        1175.0|    3134.0|    1056.0|       2.1782|           58400.0|
|   -114.6|   34.83|              46.0|     1497.0|         309.0|     787.0|     271.0|       2.1908|           48100.0|
|   -114.6|   33.62|              16.0|     3741.0|         801.0|    2434.0|     824.0|       2.6797|           86500.0|
|   -114.6|    33.6|              21.0|     1988.0|         483.0|    1182.0|     437.0|        1.625|           62000.0|
|  -114.61|   34.84|              48.0|     1291.0|         248.0|     580.0|     211.0|       2.1571|           48600.0|
|  -114.61|   34.83|              31.0|     2478.0|         464.0|    1346.0|     479.0|        3.212|           70400.0|
|  -114.63|   32.76|              15.0|     1448.0|         378.0|     949.0|     300.0|       0.8585|           45000.0|
|  -114.65|   34.89|              17.0|     2556.0|         587.0|    1005.0|     401.0|       1.6991|           69100.0|
|  -114.65|    33.6|              28.0|     1678.0|         322.0|     666.0|     256.0|       2.9653|           94900.0|
|  -114.65|   32.79|              21.0|       44.0|          33.0|      64.0|      27.0|       0.8571|           25000.0|
|  -114.66|   32.74|              17.0|     1388.0|         386.0|     775.0|     320.0|       1.2049|           44000.0|
|  -114.67|   33.92|              17.0|       97.0|          24.0|      29.0|      15.0|       1.2656|           27500.0|
+---------+--------+------------------+-----------+--------------+----------+----------+-------------+------------------+
only showing top 20 rows

In [ ]:
rich_house = df_csv.filter(col('median_income') >= 2.0)

In [ ]:
rich_house.explain()

== Physical Plan ==
*(1) Filter (isnotnull(median_income#24) AND (median_income#24 >= 2.0))
+- FileScan csv [longitude#17,latitude#18,housing_median_age#19,total_rooms#20,total_bedrooms#21,population#22,households#23,median_income#24,median_house_value#25] Batched: false, DataFilters: [isnotnull(median_income#24), (median_income#24 >= 2.0)], Format: CSV, Location: InMemoryFileIndex(1 paths)[file:/content/sample_data/california_housing_train.csv], PartitionFilters: [], PushedFilters: [IsNotNull(median_income), GreaterThanOrEqual(median_income,2.0)], ReadSchema: struct<longitude:double,latitude:double,housing_median_age:double,total_rooms:double,total_bedroo...